{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set pkgjson = load_file_data('../package.json', from_recipe_dir=True) %}
{% set project = pyproject['project'] %}

{% set name = project['name'] %}
{% set version = VERSION %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: ../dist/{{ name }}-{{ version }}-py3-none-any.whl

build:
  noarch: python
  script: {{ PYTHON }} -m pip install -vv {{ name }}-{{ version }}-py3-none-any.whl

requirements:
  build:
    - jupyter-packaging
    - jupyterlab
    - notebook
    - python
    - setuptools
    - nodejs >=18.0
    - hatch
  run:
    - python
    - bokeh 3.*
    - ipywidgets 8.*
  run_constrained:
    - jupyterlab 4.*

test:
  imports:
    - jupyter_bokeh

about:
  home: {{ pkgjson['homepage'] }}
  license: {{ project['license']['file'] }}
  summary: {{ pkgjson['description'] }}

extra:
  deploy:
    - anaconda-client
    - setuptools
    - jq
  channels:
    - bokeh
    - conda-forge
