{% set data = load_setup_py_data() %}

package:
  name: jupyter_bokeh
  version: {{ data["version"] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python setup.py build_js install --single-version-externally-managed --record record.txt

extra:
  channels:
    - bokeh
    - conda-forge

requirements:
  build:
    - jupyter-packaging
    - jupyterlab
    - notebook
    - python
    - setuptools
    - nodejs >=10.13.0
  run:
    - python
    - bokeh >=2.0.0
    - ipywidgets >=7.0.0

test:
  imports:
    - jupyter_bokeh

about:
  home: {{ data["url"] }}
  license: {{ data["license"] }}
  summary: {{ data["description"] }}

extra:
  deploy:
    - anaconda-client
    - setuptools
    - twine
    - jq
